"""An Allegretto in C major in the style of Mozart, written note by note by Claude (not generated by the model).

For comparison with what the models learn statistically: this one is composed from classical-style rules -
periodic phrasing (antecedent ends on a half cadence, consequent on a perfect cadence), a modulation to the
dominant, a varied return with a cadential trill, Alberti bass. 28 bars, 4/4, about a minute.

Run: .venv/bin/python scripts/claude_allegretto.py   -> outputs/claude/allegretto_in_c.{wav,json}
"""

import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from orchestramaker.instruments import PIANO, Note  # noqa: E402
from orchestramaker.takes import save_take  # noqa: E402

BPM = 112
NAMES = {"C": 0, "D": 2, "E": 4, "F": 5, "G": 7, "A": 9, "B": 11}


def p(name: str) -> int:
    """'C5' -> 72, 'F#4' -> 66."""
    step, rest = name[0], name[1:]
    shift = rest.count("#") - rest.count("b")
    return 12 * (int(rest.strip("#b")) + 1) + NAMES[step] + shift


# Right hand, bar by bar: (pitch, beats); each bar adds up to 4 beats.
A = [
    [("G4", .5), ("C5", .5), ("E5", 1), ("D5", .5), ("C5", .5), ("E5", 1)],                  # 1 I
    [("D5", 1.5), ("C5", .5), ("B4", .5), ("C5", .5), ("D5", 1)],                            # 2 V
    [("E5", .5), ("G5", .5), ("C6", 1), ("B5", .5), ("A5", .5), ("G5", 1)],                  # 3 I
    [("F5", .5), ("E5", .5), ("D5", .5), ("C5", .5), ("D5", 2)],                             # 4 V  half cadence
    [("G4", .5), ("C5", .5), ("E5", 1), ("D5", .5), ("C5", .5), ("E5", 1)],                  # 5 I
    [("F5", 1), ("A5", .5), ("F5", .5), ("E5", .5), ("D5", .5), ("C5", .5), ("B4", .5)],     # 6 IV - V7
    [("C5", 1), ("E5", .5), ("G5", .5), ("F5", 1), ("D5", 1)],                               # 7 I6/4 - V7
    [("C5", 1), ("E5", 1), ("C5", 2)],                                                       # 8 I  perfect cadence
]
B = [
    [("D5", .5), ("G5", .5), ("B5", 1), ("A5", .5), ("G5", .5), ("B5", 1)],                  # 9  G: I
    [("A5", 1.5), ("G5", .5), ("F#5", .5), ("G5", .5), ("A5", 1)],                           # 10 G: V
    [("B5", .5), ("D6", .5), ("G6", 1), ("F#6", .5), ("E6", .5), ("D6", 1)],                 # 11 G: I
    [("C6", .5), ("A5", .5), ("F#5", .5), ("A5", .5), ("G5", 2)],                            # 12 G: V7 - I
    [("F5", .5), ("G5", .5), ("F5", .5), ("E5", .5), ("D5", .5), ("E5", .5), ("F5", .5), ("D5", .5)],  # 13 V7 of C
    [("E5", .5), ("F5", .5), ("E5", .5), ("D5", .5), ("C5", .5), ("D5", .5), ("E5", .5), ("C5", .5)],  # 14 I - vi
    [("D5", .5), ("E5", .5), ("F5", .5), ("A5", .5), ("G5", 1), ("F5", 1)],                  # 15 ii - V7
    [("E5", .5), ("D5", .5), ("C5", .5), ("B4", .5), ("D5", 2)],                             # 16 V  retransition
]
TRILL = [("D5", .125), ("E5", .125)] * 4                                                     # cadential trill
A2 = [
    [("G4", .25), ("A4", .25), ("B4", .25), ("C5", .25), ("E5", 1),
     ("D5", .25), ("C5", .25), ("B4", .25), ("C5", .25), ("E5", 1)],                         # 17 I  ornamented
    A[1],                                                                                    # 18
    [("E5", .5), ("G5", .5), ("C6", 1), ("B5", .25), ("A5", .25), ("G5", .25), ("F5", .25), ("E5", 1)],  # 19
    A[3], A[4], A[5],                                                                        # 20-22
    [("C5", 1), ("E5", .5), ("G5", .5), ("F5", 1)] + TRILL,                                  # 23 I6/4 - V7 trill
    A[7],                                                                                    # 24
]
CODA = [
    [("G5", .5), ("E5", .5), ("C5", .5), ("E5", .5), ("A5", .5), ("F5", .5), ("C5", .5), ("F5", .5)],  # 25 I - IV
    [("G5", .5), ("E5", .5), ("C5", .5), ("E5", .5), ("F5", .5), ("D5", .5), ("B4", .5), ("D5", .5)],  # 26 I6/4 - V7
    [("C5", .5), ("E5", .5), ("G5", .5), ("C6", .5), ("G5", .5), ("E5", .5), ("C5", .5), ("G4", .5)],  # 27 I
    [("C5", 2), (None, 2)],                                                                  # 28 I
]
RIGHT = A + B + A2 + CODA

# Left hand: one Alberti figure (low, high, middle, high) per half bar, from the harmony.
ALBERTI = {"C": ("C3", "G3", "E3"), "G": ("B2", "G3", "D3"), "G7": ("B2", "F3", "D3"), "F": ("C3", "A3", "F3"),
           "C64": ("G2", "E3", "C3"), "Am": ("A2", "E3", "C3"), "Dm": ("D3", "A3", "F3"),
           "D": ("D3", "A3", "F#3"), "D7": ("D3", "C4", "F#3"), "GinG": ("G2", "D3", "B2")}
HARMONY = [("C", "C"), ("G", "G"), ("C", "C"), ("G", "G"), ("C", "C"), ("F", "G7"), ("C64", "G7"), ("C", "C"),
           ("GinG", "GinG"), ("D", "D"), ("GinG", "GinG"), ("D7", "GinG"), ("G7", "G7"), ("C", "Am"), ("Dm", "G7"),
           ("G", "G"),
           ("C", "C"), ("G", "G"), ("C", "C"), ("G", "G"), ("C", "C"), ("F", "G7"), ("C64", "G7"), ("C", "C"),
           ("C", "F"), ("C64", "G7"), ("C", "C"), ("END", None)]


def main():
    rng = random.Random(0)
    beat = 60 / BPM
    bar_len = 4 * beat
    # Ritardando over the last two bars: later beats get longer.
    def at(bar, beats):
        t = bar * bar_len + beats * beat
        slow_from = 26 * bar_len
        return t if t < slow_from else slow_from + (t - slow_from) * (1 + 0.12 * (t - slow_from) / (2 * bar_len))

    notes = []
    for b, bar in enumerate(RIGHT):
        assert abs(sum(d for _, d in bar) - 4) < 1e-6, f"bar {b + 1} does not add up to 4 beats"
        pos = 0.0
        for name, dur in bar:
            if name:
                # Phrase shape: louder towards each phrase's third bar, softer at cadences.
                arc = [0, 6, 10, 2][b % 4]
                start = at(b, pos) + rng.uniform(-0.008, 0.008)
                notes.append(Note(p(name), max(start, 0), (at(b, pos + dur) - at(b, pos)) * 0.95,
                                  int(74 + arc + rng.randint(-3, 3))))
            pos += dur
    for b, (first, second) in enumerate(HARMONY):
        if first == "END":  # final tonic chord, held
            for name in ("C2", "C3", "E3", "G3"):
                notes.append(Note(p(name), at(b, 0), (at(b, 3.8) - at(b, 0)), 60))
            continue
        for half, chord in enumerate((first, second)):
            low, high, mid = ALBERTI[chord]
            for k, name in enumerate((low, high, mid, high)):
                pos = 2 * half + 0.5 * k
                notes.append(Note(p(name), at(b, pos) + rng.uniform(-0.006, 0.006),
                                  (at(b, pos + 0.5) - at(b, pos)) * 0.9, 52 + (6 if k == 0 else 0) + rng.randint(-2, 2)))
    meta = {"title": "Claude: Allegretto in C major, in the style of Mozart", "style": "mozart", "instrument": "piano",
            "composer": "Claude (written note by note, not generated by the model)", "source": "claude"}
    path = save_take(ROOT / "outputs/claude", "allegretto_in_c", [("as written", [(PIANO, notes)])], meta)
    print(f"{len(notes)} notes, {max(n.end for n in notes):.0f} s -> {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
